### ISSUE TITLE
facebook login

### ISSUE THREAD

**Issue by cmazuc** [cmazuc/scarfage#1]
http://www.socialmediaexaminer.com/10-ways-to-add-facebook-functionality-to-your-website/
https://pythonhosted.org/Flask-OAuth/
https://github.com/mitsuhiko/flask-oauth/blob/master/example/facebook.py

**Comment by subiki** [comment]
Is bolting on FB still an option with our current direction?

**Comment by cmazuc** [comment]
yes

**Comment by cmazuc** [comment]
Looks like we should start here to get an API key

https://developers.facebook.com/apps

mind doing the needful?

**Comment by cmazuc** [comment]
Made some progress on this today:

https://test.scarfage.com/login_with_facebook

Doesn't actually log you in yet but returns some useful data. Should have this hammered out in a few days.

**Comment by cmazuc** [comment]
https://test.scarfage.com/

Everything seems to be working as intended right now but I could use some testing of this feature. Note that once you bind your Facebook account to a Scarfage account it can't be rebound to a different one. Your passwords should still work though. I don't plan to support multiple accounts with this feature.

**Comment by subiki** [comment]
Error 500 on the test site homepage if not logged in.

**Comment by subiki** [comment]
You can't link an account to Facebook without logging in, but the UI to link Facebook disappears once logged in. I was able to link it using two open tabs and working around it. Needs an option in Profiles to link to Facebook and better instructions. Works great after linking though.

**Comment by cmazuc** [comment]
There is already a link on your profile to add fb auth, agreed that it's 
probably not clear enough though

**Comment by cmazuc** [comment]
Let me know if you're still able to repro the 500 after this update to the test site

**Comment by cmazuc** [comment]
Now that I'm looking at this again I'm not sure how to make it more obvious. People seem to be finding the 'edit your profile' link on their profiles without issue so while ugly the profile links are clearly functional. Clicking log in with facebook redirects you to create a username or link an account if you don't already have a linked account. There's also a link on the new user signup page itself.

**Comment by cmazuc** [comment]
I'm ready to push this to the site if you're happy with it

**Comment by subiki** [comment]
I noticed if I login with my scarfage account, the profile page still offers to link to facebook. clicking it changes to "linked to facebook". when i login with facebook it shows linked. logging back in with scarfage account doesnt show linked. it doesn't seem to have any negative impact other than possibly being confusing.

**Comment by cmazuc** [comment]
Give it a try now, should be fixed.

**Comment by cmazuc** [comment]
This is now live
