### ISSUE TITLE
Bug report for FLAG option.

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#101]
I have zero data, but I feel there is a bug in the approval process for newly uploaded images. This is the anecdotal data I can provide.
New item is created and picture uploaded.
Appears in MOD tab for review.
I click approve.
5 minutes later it appears in the MOD tab as USER FLAGGGED for review again.

I thought it was someone clicking the flag button too much, but it is 100% of the items created need to be approved twice.

**Comment by cmazuc** [comment]
the image flag link didn't have nofollow so it might have been bots. I'm not able to repro so let me know if this persists after the next site update and I'll dig into the logs

**Comment by cmazuc** [comment]
seems resolved to me, reopen if you're still seeing this
