### ISSUE TITLE
Game day scarf in profile

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#102]
#88 
The community wants to have an editable field to describe themselves to others. One request was to have a place to list which scarf is your "game day" scarf that you wear to matches.

**Comment by cmazuc** [comment]
Next site update will include a profile summary feature

**Comment by cmazuc** [comment]
Profile summary feature is minimal but functional.

**Comment by subiki** [comment]
any way to allow links?
https://www.scarfage.com/user/scarfage#userinfo
<a href="https://www.facebook.com/groups/scarfage">FB Group</a> 
or
[Github Wiki](https://github.com/cmazuc/scarfage/wiki)

**Comment by cmazuc** [comment]
yea, we can add markdown support

**Comment by cmazuc** [comment]
last commit adds markdown support, this will go out with the next site update. it'll be live on test shortly

**Comment by cmazuc** [comment]
https://test.scarfage.com/user/scarfage

**Comment by subiki** [comment]
markdown works, seems to be a minor bug somehow. check the link above, here is the code.
The second header is not read correctly, no big deal.
# [Github Wiki](https://github.com/cmazuc/scarfage/wiki)
# [FB Group](https://www.facebook.com/groups/scarfage)

**Comment by cmazuc** [comment]
Can you double check the markup on the test site? I'm pretty sure the test you did was HTML and markdown. It is intentional that arbitrary HTML will not be rendered as part of user profiles.

**Comment by cmazuc** [comment]
You meant on the main site, I see what you mean now.

**Comment by subiki** [comment]
```
# [Github Wiki](https://github.com/cmazuc/scarfage/wiki)
# [FB Group](https://www.facebook.com/groups/scarfage)
```

**Comment by cmazuc** [comment]
looks like it's a bug in the html escaping bit, should be an easy fix

**Comment by cmazuc** [comment]
I switched the module used for escaping, not sure if it was a bug in that or not but either way it seems to be fixed now

**Comment by cmazuc** [comment]
Also urls will automatically be links
