### ISSUE TITLE
Development Setup DB issue

### ISSUE THREAD

**Issue by oamike** [cmazuc/scarfage#103]
Followed Dev setup - ran python run.py.
When submitting registration form, get this error in python output:

ERROR:scarf.core.sql:MySQL error: (1146, "Table 'scarfage.strings' doesn't exist")

Browsed the scarfage DB, indeed there is no scarfage.strings table.
perhaps the scarfage.sql needs to be updated and pushed?

[oamike]

**Comment by oamike** [comment]
restarted Mac - even though my initial user was created fine, next new user submit results in same error.

**Comment by cmazuc** [comment]
Sorry about that, should be fixed now.
