### ISSUE TITLE
can i haz write access plz?

### ISSUE THREAD

**Issue by oamike** [cmazuc/scarfage#104]
Please fill out as much of this as you can

What is your username?

Did you receive a specific error message?

What was the URL that gave an error?

Approximately what time did the error occur (please include time zone)?

**Comment by oamike** [comment]
I would like to be able to edit the wiki.
I have set up the dev environment on a Macbook Pro - and think the changes will help others.

I cloned the wiki repo, but do not have write access to the wiki content.
Is there anyway to get in-page editing?

Thanks!

**Comment by cmazuc** [comment]
The wiki has been unlocked, please reopen if you aren't able to edit it.
