### ISSUE TITLE
trade requests v messages

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#111]
Bug: When opening an initial trade request any message added to the request does not show in the recipients message window. it shows in the trade window, and any later replies will appear in the messages window. 

+it is hard to see when you have a new trade or message, a combined view would be better. 
+notifications in the menu even better.

**Comment by cmazuc** [comment]
On the back end trades are actually just a type of private message so it would be easy to change the template to show them both in the same area. After using it for a bit I agree that the current layout is clunky and that a combined view would be better.

**Comment by cmazuc** [comment]
@cherz: I can combine these in the template if you want, I just don't want to stomp on any changes you might have in the works. Please assign back to me if you weren't planning on working on the profile template soon. Thanks!

**Comment by cherz** [comment]
Go for it. I'm looking at tacking sorting on Stats. Thanks!

**Comment by cmazuc** [comment]
Trades are now included with the other messages. Notifications are being tracked on #75, closing this out.
