### ISSUE TITLE
Max-Width for scarves on homepage & search results?

### ISSUE THREAD

**Issue by cherz** [cmazuc/scarfage#115]
How wide do we want to make the scarf images on the homepage and search results page? Currently it's set to 500px x 200px. Can we go up to 640px x 256px? We'll still maintain a 5:2 ratio.

**Comment by cmazuc** [comment]
That's fine with me, assigning to Jason to see if he has any input

**Comment by subiki** [comment]
I just work here, do what you think is best.

**Comment by cherz** [comment]
Bumping it up to 640x256. Those are nice mathy numbers...
