### ISSUE TITLE
double image upload

### ISSUE THREAD

**Issue by cleech** [cmazuc/scarfage#116]
Please fill out as much of this as you can

What is your username?
cleech

Did you receive a specific error message?
no

When uploading images, I had several show up twice.  My browser may have generated two click events, but perhaps they should be filtered somehow or the file name cleared when the first one is processed to prevent this.

**Comment by subiki** [comment]
https://www.scarfage.com/item/422

**Comment by subiki** [comment]
I deleted the duplicate file: Jun 10, 10 55 04 AM.jpeg

**Comment by subiki** [comment]
https://www.scarfage.com/item/419
Jun 10, 10 18 04 AM.jpeg

**Comment by cmazuc** [comment]
Maybe a bug with safari? I'm seeing duplicate requests from your browser:

xx.xx.xx.xx - - [10/Jun/2016:17:19:54 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/418" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
xx.xx.xx.xx - - [10/Jun/2016:17:20:18 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/418" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
xx.xx.xx.xx - - [10/Jun/2016:17:20:45 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/419" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
xx.xx.xx.xx - - [10/Jun/2016:17:20:45 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/419" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
xx.xx.xx.xx - - [10/Jun/2016:17:21:12 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/419" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
xx.xx.xx.xx - - [10/Jun/2016:17:34:36 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/420" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
xx.xx.xx.xx - - [10/Jun/2016:17:34:48 +0000] "POST /newimg HTTP/1.1" 302 273 "https://www.scarfage.com/item/420" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"

**Comment by cmazuc** [comment]
I plan to rate limit uploads by IP address in the future, that should mitigate this issue but I have no idea why your browser would be generating duplicate requests.
