### ISSUE TITLE
Bulk Message Handling

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#122]
Would be more efficient to select multiple messages/trades and delete them. Deleting 20+ messages takes almost 5 minutes.

**Comment by cmazuc** [comment]
just needs js buttons so no page load is involved

**Comment by cmazuc** [comment]
the new ui changes should help with the nav issues you were having before, let me know if this is good enough for now

**Comment by subiki** [comment]
the current functionality leaves the user on the message page after hitting the trash. This works for now, it's a little smoother than navigating back to messages like before. Unless you get 100 messages, this shouldnt be a priority feature.

**Comment by cmazuc** [comment]
now has JS to prevent the page reload
