### ISSUE TITLE
Add additional search options

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#124]
#88 
Users would like to be able to search for other users by their alias.

**Comment by cmazuc** [comment]
I updated the robots.txt today to clean up some of the junk results but this is probably the best we'll be able to do for now:

https://cse.google.com/cse/publicurl?cx=015246425163706330590:ftbiji0yqbo

**Comment by cmazuc** [comment]
Added google permissions for both of you

**Comment by cmazuc** [comment]
closing in favor of #45
