### ISSUE TITLE
site redirect!

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#126]
#88 
Facebook group reported a hijacking.

https://www.scarfage.com works correctly.
http://www.scarfage.com forwards to http://www.urldaikaiju.com/

**Comment by cmazuc** [comment]
should be fixed shortly

**Comment by cmazuc** [comment]
fixed the nginx config, looks good now

**Comment by cmazuc** [comment]
this was a misconfiguration, not a hijacking btw
