### ISSUE TITLE
Status of item borked

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#135]
New UI changes in the last day have broken the ability to tell an items list status to the user.
I have all 8 function buttons available, but cannot tell if an item is already on a list or needs removed.
![indicators](https://cloud.githubusercontent.com/assets/12373824/18768656/b26ed89e-80db-11e6-8900-b928a20f6510.png)

**Comment by subiki** [comment]
This is possibly an intermittent bug. I am able to reproduce by not consistently.

**Comment by cmazuc** [comment]
please try a ctrl-f5 refresh and let me know if you're still able to repro

**Comment by cmazuc** [comment]
This change should help if it's stale JS:

https://github.com/cmazuc/scarfage/commit/b73004b1e2bcec120f76ee18ff7e76f64524863c

**Comment by cmazuc** [comment]
https://github.com/cmazuc/scarfage/commit/1b3cdae6977d6dc5d4ebb249775b0cb3d617c0a5 adds a loading spinner to give better feedback
