### ISSUE TITLE
Stats Request

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#136]
https://www.scarfage.com/stats

Possibly also include:
Number of registered users
Number of active users in the last 48 hours possibly with names
Total number of items on the site
least wanted items
most wanted items
least collected items
most collected items
number of new scarfs in past week
number of edits in past week
list of items without pictures

**Comment by cmazuc** [comment]
Will track on https://github.com/cmazuc/scarfage/projects/5, add stuff into the ideas bucket in there please
