### ISSUE TITLE
site health stats on admin portal

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#147]
It could be useful to have a spapshot of server metrics on the admin page. Site usage stats and page loads instead of the AWS console. 
Google trends could also be used.
https://www.google.com/trends/explore?date=today%2012-m&q=scarfage

**Comment by cmazuc** [comment]
We'll probably do basic stuff someday but cloudwatch graphs aren't embeddable so no quick win here.

**Comment by oamike** [comment]
Leaving this for future - use geckoboard to visualize - link directly to it. Have to check for free version...
