### ISSUE TITLE
Adjustable Ban Hammer

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#148]
Admins should have the ability to delete a user from the site. In case of abuse this would be useful to have an option to remove all items created by that user, and potentially roll back any changes. This would need a list of all changes before proceeding just for oversight. Specifying a time frame for deletions would be good for hacked accounts without destroying useful content.

**Comment by cmazuc** [comment]
Let's revisit this if it's warranted, I don't feel like there's really a need for this right now or in the near future. If anything truly fucked happens I can script a fix.

**Comment by cmazuc** [comment]
Also, I double checked our backups last night and we're definitely good there. We have nightly snapshots for the past 30 days so rollback is always an option as well.
