### ISSUE TITLE
search pagination on mobile

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#152]
Page buttons on top of long lists won't scale on mobile.
![14446096_10154576819242803_662322677663277056_n](https://cloud.githubusercontent.com/assets/12373824/18819368/8648e2b2-8344-11e6-96f7-5c01795945f0.jpg)

**Comment by cmazuc** [comment]
we can hide the top one if the window's width is less than some value

**Comment by cmazuc** [comment]
or only show x pages at a time, would probably be cleaner anyway
