### ISSUE TITLE
browser usage stats

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#157]
How can we see data on mobile v desktop and which browser users prefer?

**Comment by oamike** [comment]
Hook up google analytics - but I thought you did already... hmm.

**Comment by oamike** [comment]
This may help:
http://webmasters.stackexchange.com/questions/74609/google-analytics-how-to-see-more-detailed-browser-and-os-info-at-same-time

**Comment by cmazuc** [comment]
CloudFront has this data in the AWS console
