### ISSUE TITLE
unable to save profile edits

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#162]
jhance reports he is unable to change his avatar or gameday/ww scarfs. He gets a confirmation message but does not save. I am unable to reproduce with two other accounts. errors occur around 1:50pm local time  9/28/16.

https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=UWSGI-ScarfageProd;stream=i-8a98a01f;filter=jhance;tz=Local

**Comment by subiki** [comment]
user kdc824 also reports the issue.

**Comment by cmazuc** [comment]
testing a fix now, only newer users would be affected

**Comment by cmazuc** [comment]
Give it another try now, should be resolved. Please close out if you can confirm they're both good now.
