### ISSUE TITLE
Item Action buttons on collections page

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#168]
Can we add item action buttons to collections pages belonging to other users.
Buttons currently available on my own collection only.

**Comment by cmazuc** [comment]
I tried it when I first added the status boxes everywhere and it looked *really* confusing to see them on other people's collection pages. I'm thinking that the collections feature should be reimplemented to not be tied so closely to a particular user (also for #149), that should solve a bunch of problems including this one IMO.

**Comment by cmazuc** [comment]
closing in favor of #149
