### ISSUE TITLE
Libraries - user controlled categorization of tags in tree form

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#21]
allow users to create custom sorting trees for their scarfs. they should be able to have this drop down available on scarf pages as an option to classify after creating or adopting one. users can share their trees (libraries) and vote up or down, eventually this can be averaged and crowd sourced. The user would be able to select from tags already in the database, or create a new entry. This will probably create a need for aliases and linking similar clouds. acronyms or full spelling should be considered the same if possible. 
ultimately users need to have a friendly way to use trees to categorize their scarfs. they should be able to add a scarf they are viewing to any level in the tree, or create a new level and add it. these trees would be personal, but they can copy others to their tree. having multiple libraries would be useful also, for example tracking away day collections. Or these are the scarfs that I want to collect from the other teams. 

Timbers > Supporters Scarfs > Regional Scarfs> TA:CO > 
Create My Collection: Whateveriwanttocallit
Choose Tag to create parent: 
		Timbers
Choose Tag(s) to create child:          Cancel to previous parent.		add scarfs.
		Front Office Scarfs
		Supporters Scarfs
Choose child group or create more:
		Supporters Scarfs
Choose Tag(s) to create child:          Cancel to previous parent.		add scarfs.
		Regional Scarfs
		Section Scarfs
		Charity Scarfs
		No Pity Fringe
Choose child group or create more:
		Regional Scarfs
Choose Tag(s) to create child:          Cancel to previous parent.		add scarfs.
		TA:CO
		LSB
		ECP
		TANA
		TANS
Choose child group or create more:
		TA:CO

**Comment by cmazuc** [comment]
+ moderated tags that have to be requested, keep trolls from spamming other people's auto-collections

**Comment by subiki** [comment]
This feature request will be replaced by a custom collection library for users to mark and share on their profile. The overall heirarchy by default on the site will be determined by meta tags linking parent and children with moderators. Meta tag changes will need to be approved by admins.

**Comment by cmazuc** [comment]
meta tags proved to be troublesome to use, closing this out in favor of #149
