### ISSUE TITLE
? breaks upload

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#25]
![10001153_1074142602613368_6951565059725886630_o](https://cloud.githubusercontent.com/assets/12373824/8321403/546d73d0-19db-11e5-9f80-254ed6f4f42f.jpg)

The attached file borked upload. It created an entry for the scarf, but 404 page after clicking the link from Home.

**Comment by cmazuc** [comment]
it's the question mark in the title

**Comment by cmazuc** [comment]
fixed
