### ISSUE TITLE
Privacy Options

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#32]
1) The current build allows the option to hide, but visible by default. That should be flipped.
Profile collections should be hidden by default. When uploading or claiming a scarf as owner it should remain hidden from other users.
2) Have an option to hide/show entire collection for easy toggle.
optional: Mark items as always hidden or locked.
3) Items marked willing to trade should be visible by default, but also allow the option to hide. Users may want to keep private lists for personal tracking.

**Comment by cmazuc** [comment]
1: https://github.com/cmazuc/scarfage/commit/9add5e58e73492c509a0f999e0d9568f137ed62a

2: That can be done through the template via JS, there isn't anything on the backend that needs to be changed.

3: Can do in a future version based on demand.

**Comment by cmazuc** [comment]
#149
