### ISSUE TITLE
duplicate items much

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#36]
After creating an item there is a save button on the confirmation screen that allows for a duplicate item.

**Comment by cmazuc** [comment]
I'm unable to repro, not sure what you mean here.

**Comment by subiki** [comment]
i cant repro it now, but take a look at the main page with duplicate listings of the really really long name

**Comment by subiki** [comment]
reproduced this error by using a title of excessive length, it cuts off but does not handle it. The save button persists and allows the user to spam it.

**Comment by subiki** [comment]
seems to be 200 character limit and drops any data afterwards, but breaks the SAVE button.

**Comment by cmazuc** [comment]
I'm able to repro. How big do you want the title limit to be?

**Comment by subiki** [comment]
![img_20160207_112808](https://cloud.githubusercontent.com/assets/12373824/12874901/ca9bfae8-cd92-11e5-9467-791fd71b7421.jpg)

**Comment by subiki** [comment]
i think 64 characters should be sufficient for a max.
