### ISSUE TITLE
resize operation generates DecompressionBombWarning exception and breaks moderation

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#39]
received somewhat helpful error page when uploading an image.

413 Request Entity Too Large
nginx

**Comment by cmazuc** [comment]
how big was the image. Can you attach it here?

**Comment by subiki** [comment]
![img_20160207_112808](https://cloud.githubusercontent.com/assets/12373824/12874906/e3331a64-cd92-11e5-9188-026b6498c9a7.jpg)

**Comment by subiki** [comment]
Also returned an unformatted error page.

**Comment by cmazuc** [comment]
Images up to 10MB should work fine now. The code itself supports huge images but I needed to make some changes to the db and nginx configs.

Note that images below the file size limit but above the pixel limit set in PIL will throw a DecompressionBombWarning exception on preview or thumbnail generation. The default is int(1024 * 1024 * 1024 / 4 / 3) or appx 9500 * 9500. That's pretty damn big. I don't really feel the need to change this right now.

**Comment by cmazuc** [comment]
Actually, that decompression bomb exception breaks moderation, reopening.

**Comment by cmazuc** [comment]
No longer seems to be an issue, closing
