### ISSUE TITLE
reassign picture to different item

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#42]
That's not this scarf. Okay which one is it or move to new item?

**Comment by subiki** [comment]
We have a few ways to slowly dedupe items with moderators help. Flagging items for duplicates and manually doing it will work short term. renaming the item to an existing item and having an auto merge option for mods would be easier.

**Comment by cmazuc** [comment]
Moderators can now enter a new itemid to reparent an item. Items will now also show the ID next to the name for moderators. We should eventually wrap it in a selection UI but this should be good enough for now.
