### ISSUE TITLE
add note when flagging image

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#43]
In case someone wants to let us know more information about why they flagged an image, there should be a text field they can use.

**Comment by cmazuc** [comment]
Flagging is only meant to be used for offensive or irrelevant content, if it isn't obvious then it shouldn't be flagged. If there's another use case you have in mind here then let's have a conversation about implementing that separately.

**Comment by oamike** [comment]
Might be nice to have an admin only visible flag for - missing info/images. But another thread / issue addresses this through a view that can be filtered for missing data...
