### ISSUE TITLE
Better Search

### ISSUE THREAD

**Issue by cmazuc** [cmazuc/scarfage#45]
Will implement soon:
+ Add tags to item search

Other requests:
+ multiple term support
+ Team search (default tag term addition)
+ Advanced item search
 + tag
 + added
 + last edited
 + description
 + Image count

Implemented:

+ Member search by username
+ Tag search

**Comment by cmazuc** [comment]
basic search in place, moving to release milestone to revisit this

**Comment by subiki** [comment]
things to search note:
by quantity
description info
uploader
last edited by
tags
filter results by have/want/trade

**Comment by cmazuc** [comment]
Summarize this so far:

+ Advanced item search
+ Member search by username
+ Tag search

**Comment by cmazuc** [comment]
Will track on https://github.com/cmazuc/scarfage/projects/4
