### ISSUE TITLE
error 500 page

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#49]
the error 500 page could have a text entry box to enter relevant feedback about how you got there. it would make it faster for bug testing, and easy for users to write direct instructions later.

**Comment by cmazuc** [comment]
I'd prefer to keep issue tracking here on github. We can tell from the logs if errors are occurring, I saw you get some 500s yesterday and was able to use the logs to troubleshoot as they have your referrer and a stack trace. A grep for your IP gives me the full path you took to get there.
 
In any case if the site is crashing then we can't count on it to do anything useful at that point. Ideally we won't ever generate a 500 as all exceptions would be handled gracefully.

**Comment by subiki** [comment]
This was more for user feedback in the future. A simple email template available for logged in users to tell us how they broke it. It could email the admin or debug email and I will repro and cut an issue.
