### ISSUE TITLE
mixed images

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#57]
Please fill out as much of this as you can

What is your username? subiki

Did you receive a specific error message?

What was the URL that gave an error?

Approximately what time did the error occur? 245pm 2/27/16

https://www.scarfage.com/item/173

When i uploaded an image named back to this item the image appeared as an ECS scarf. No  object for this ECS image exists though.

https://www.scarfage.com/image/23 is wrong.

https://www.scarfage.com/image/23/full appears correct though.

**Comment by cmazuc** [comment]
not a bug, the main site uses cloudfront for image caching. you're seeing an artifact of the db being dumped and item ids overlapping. give it a few days for the cache to expire out

https://d2tx6l6dxpjuj3.cloudfront.net/image/23/preview

the test site doesn't use CF for caching. if we ever needed to do something like this once the site is live we could invalidate the cashe but I'm pretty sure there's a charge for doing that

**Comment by cmazuc** [comment]
looks like first few are free, I just issued an invalidation for that image and it should update soon

**Comment by cmazuc** [comment]
fixed

**Comment by subiki** [comment]
We can just do one more before db goes prod and be aware of it. No plan to
fix
