### ISSUE TITLE
Add/remove items to existing trade offer.

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#58]
currently you have to create a new trade offer when haggling. It should be easier to remove and add different items to a trade stack.

also it would be nice to indicate "pick one" from these offered scarfs, or indicate that ALL of these scarfs are for trade as a bundle.

**Comment by cmazuc** [comment]
Removal of items is accomplished by declining to trade that item, they'll stay in the list but are now greyed out. Adding additional items to existing trades is now supported.
