### ISSUE TITLE
Anon permissions

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#60]
Anonymous users should view and flag only. They currently have permissions to upload and edit.

**Comment by cmazuc** [comment]
I'm not sure I agree, let's revisit this if it becomes a problem. I plan on adding rate-limiting so that will reduce the amount of damage someone can do before we notice.

**Comment by subiki** [comment]
Let's be proactive and not wait for something to go wrong. Can we remove anon permissions to edit?

**Comment by cmazuc** [comment]
yep

**Comment by cmazuc** [comment]
https://test.scarfage.com/

let me know if thats what you had in mind

**Comment by subiki** [comment]
That's a good start, blocks the easiest attacks. Can we hide the new item link, upload image info, and edit icon altogether?

**Comment by cmazuc** [comment]
> That's a good start, blocks the easiest attacks.

I'm not sure what else would need to be locked down right now, what got missed?

**Comment by cmazuc** [comment]
I think leaving them visible and letting the user know why it won't work would get more people to sign up, esp now that facebook login is merged and deployed. Please reopen or create a new issue if there's something I forgot to lock.
