### ISSUE TITLE
error 500 found with image and deleted item

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#61]
I created an item named delete me.
https://www.scarfage.com/item/179
I uploaded an image.
https://www.scarfage.com/image/26
I deleted the item.
I flagged the item for review by visiting the direct link above.
In the moderation tab this link for review gives error 500.
https://www.scarfage.com/mod/image/26
The item correctly returns 404.
https://www.scarfage.com/item/179

Not sure what to do about this? Remove the image flag when item is deleted, or moderate the image itself separate from the item? we should keep the images after an item is deleted, or have an option to include associated photos. 
what do we do with orphaned images?

**Comment by cmazuc** [comment]
fixed by latest commit
