### ISSUE TITLE
New Item Template

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#64]
Have a few simple questions built into the text field for new item description to guide content. 
We could also moderate these questions into existing descriptions and bold them to encourage users to answer them and fill out the item profile with depth. Once they are answered we could remove the question. 

for example

Who made this?
How many?
When?
Why?

**Comment by cmazuc** [comment]
I feel like we'd end up with a lot of unnecessary boilerplate left over in item descriptions. Maybe have a list of submission guidelines next to the text box with an example description? I believe we can achieve the same effect with much less complexity and dev time.

**Comment by cmazuc** [comment]
I don't ever see myself implementing this, closing it out. I added some notes to the item editing page, feel free to edit it some more.
