### ISSUE TITLE
broken item

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#74]
during user testing an item was created that seems to break the system, it was uploaded by user dirtytoes and causes an unhandled error when viewing, and error 500 otherwise. 
https://www.scarfage.com/item/186

I have contacted the user for more data.

**Comment by subiki** [comment]
You can currently create a new item without an image upload. Unhandled error when viewing afterwards.
https://www.scarfage.com/item/193

**Comment by subiki** [comment]
Broken secondary image upload to an existing object. related. 
https://www.scarfage.com/item/187

**Comment by cmazuc** [comment]
these items appear to have been deleted

**Comment by cmazuc** [comment]
I've added some better logging for crashes so we can properly troubleshoot this sort of stuff that's hard to repro.

**Comment by cmazuc** [comment]
can't repro
