### ISSUE TITLE
Clicking on Tag text

### ISSUE THREAD

**Issue by dontexpectmuch** [cmazuc/scarfage#76]
Please fill out as much of this as you can
I clicked on the text of a tag instead of the  icon and I got an Oh Noes Table flip 500 error.
The text was red vs. the standard blue
I verified it on two pages (2016-02-27 21:26:37 - adidas and 2016-03-10 02:31:30 - Zelda
The issue seems to be resolved now, and those tags are gone

What is your username?
dontexpectmuch
Did you receive a specific error message?

What was the URL that gave an error?

Approximately what time did the error occur?
9:05pm 03/11/16

**Comment by cmazuc** [comment]
I was in the process of stripping out some tag stuff we were testing that didn't work out, should be fixed now. Please reopen if you see this again, I have better logging in place now that should help troubleshoot these kinds of errors. Thanks!
