### ISSUE TITLE
Create links in descriptions.

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#84]
Is there a markup to allow links in the item descriptions? It only shows plain text.

https://www.scarfage.com/item/191

**Comment by cmazuc** [comment]
Markdown is supported for all descriptions, most if not all of this should work:

https://daringfireball.net/projects/markdown/syntax

This is [an example](http://example.com/) inline link.

I can also re-enable the wiki-style link feature where you do something like [[Item Title]] instead. I'd need to add some code to redirect based on item name but when we used the item titles in URLs before we ran into issues with some characters. Unfortunately there really isn't a good way to handle those cases in a way that would be compatible with the wiki link feature of the markdown package.

**Comment by subiki** [comment]
https://www.scarfage.com/item/243

resolved with example item
