### ISSUE TITLE
Library account

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#85]
Can we create a system account  with a profile that auto adds every scarf to their collection and is visible? The Library.

**Comment by cmazuc** [comment]
The short answer is yes. This functionality could probably be better implemented a different way though, can you tell me more about what you would use this for?

**Comment by subiki** [comment]
After our chat today we should just have a Library link at the top that leads to an alphabetic and paginated list of all items for browsing. Similar utility with a simpler implementation.

**Comment by subiki** [comment]
it would be very useful to have have/want/trade buttons on the library page as well, if there is a way to select multiples it would be even more useful.

**Comment by subiki** [comment]
pickles, this is a priority feature. we need a library link in the top menu that displays all scarfs. for now i am using the scarfage user account to add all scarfs and it is incredible manual.

**Comment by cmazuc** [comment]
self-assigning to add the interface for this

**Comment by cmazuc** [comment]
I still need to have it return results in JSON format but this should work for now:

https://www.scarfage.com/item/search?query=
