### ISSUE TITLE
Collections Page with Trade Items Available

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#87]
the collections page under a user profile currently shows a HAVE and WANT list. It should contain a TRADE AVAIL list as well. You can currently offer a trade for an item from the HAVE, but if a user has a few hundred scarfs in their collection it would be useful to filter out just the ones open for trade.

https://www.scarfage.com/user/subiki#collections

side question, are all "trade items available" visible to other users or does it follow similar opt in from the HAVE list?

**Comment by subiki** [comment]
Specific user AVAIL lists are important but we could also expand this into a general TRADE AVAIL tab that combines all users, with a number listed next to each item for how many users have it avail. It should be a scalable solution. Or integrate that data into the Library tab from https://github.com/cmazuc/scarfage/issues/85

**Comment by cmazuc** [comment]
Collections are now sorted by their owner's willingness to trade and are marked as such; all available items will now show at the top. I'll eventually add pagination and sorting but I think this largely meets the spirit of your request.

https://www.scarfage.com/user/subiki/collections
