### ISSUE TITLE
Move the Logout button

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#89]
#88 
People are clicking on the logout button by accident in the top bar, especially on the mobile version. it should be moved to the profile page instead.

Additionally the Profile button is being clipped off screen and needs to be moved left towards the main menu buttons.

**Comment by cherz** [comment]
I hid the logout on mobile for now. I am going to do some clean up on the nav for mobile. Remove the scrolling and such. Closing this one for now and opening an overall "Nav" ticket.
