### ISSUE TITLE
Remove Anon permission to flag images - avoid mod spam

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#90]
#88 

Unregistered users can still click the flag button which can create a lot of spam in the moderators queue. Removing that button from Anon access and having an indication of WHO flagged for review will help.

**Comment by cmazuc** [comment]
still seeing spam? queue is empty now fwiw

**Comment by cmazuc** [comment]
resolving for now, if this gets abused in the future I'll implement IP bans
