### ISSUE TITLE
error 500 on signup again

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#92]
What is your username? scarfage while registering a new account. 

Did you receive a specific error message? error 500, but still got registered successfully. received email confirmation and account worked when i logged in. is it trying to auto log me in and failing? are you supposed to register and then log in again?

Approximately what time did the error occur (please include time zone)? 10:30 pm 5/19/16

**Comment by cmazuc** [comment]
will continue to monitor for exceptions but I think this is fixed now
