### ISSUE TITLE
Modify list status from collection view

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#95]
When viewing another users collection profile, it should be easy to add scarfs to my HAVE/WANT/TRADE lists. The code should be easily modified from the existing item page.
This feature would prevent the need to click on each item in a collection in order to add it to yours and then return back to the collection to look for the next one you are missing.
https://www.scarfage.com/user/scarfage#collections

**Comment by cmazuc** [comment]
closing in favor of #105
