### ISSUE TITLE
Admin site cleanup

### ISSUE THREAD

**Issue by subiki** [cmazuc/scarfage#96]
We need to be able to sort or filter the accounts from the admin site. There will be too many accounts to find what you need, sorting by column would work.

https://www.scarfage.com/admin

**Comment by subiki** [comment]
@cherz can you figure out a way to choose sorting for columns in the admin site, it currently shows accounts in order by last login only.

**Comment by cmazuc** [comment]
https://github.com/cmazuc/scarfage/projects/6
